/* Generated By:JavaCC: Do not edit this line. LenguajesProyConstants.java */
package Compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LenguajesProyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PUBLIC = 1;
  /** RegularExpression Id. */
  int PRIVATE = 2;
  /** RegularExpression Id. */
  int CLASS = 3;
  /** RegularExpression Id. */
  int IF = 4;
  /** RegularExpression Id. */
  int WHILE = 5;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int LBRACE = 8;
  /** RegularExpression Id. */
  int RBRACE = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int ASIGNACION = 11;
  /** RegularExpression Id. */
  int MAYORQUE = 12;
  /** RegularExpression Id. */
  int MENORQUE = 13;
  /** RegularExpression Id. */
  int MAYORIGUALQUE = 14;
  /** RegularExpression Id. */
  int MENORIGUALQUE = 15;
  /** RegularExpression Id. */
  int IGUALQUE = 16;
  /** RegularExpression Id. */
  int DIFERENTEDE = 17;
  /** RegularExpression Id. */
  int BOOLEAN = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"public\"",
    "\"private\"",
    "\"class\"",
    "\"if\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"boolean\"",
    "\"int\"",
    "<INTEGER_LITERAL>",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
  };

}

